const P={A:[
{b:"A1",n:"Goblet Squat",s:3,r:"8–10",l:"17 kg",w:"Beine und Core bei stabiler Knieachse.",c:"Breiter angenehmer Stand, langsam absenken.",v:"https://www.youtube.com/results?search_query=goblet+squat+technique"},
{b:"A2",n:"Chest Supported Row",s:3,r:"8–10",l:"9 kg",w:"Mittlerer Rücken ohne unnötige HWS-Belastung.",c:"Brust an der Bank, Nacken lang, Ellbogen Richtung Hüfte.",v:"https://www.youtube.com/results?search_query=chest+supported+dumbbell+row+technique"},
{b:"B1",n:"Floor Press",s:3,r:"8–10",l:"13 kg",w:"Druckkraft bei stabilem Handgelenk.",c:"Neutraler Griff, Schulterblätter stabil.",v:"https://www.youtube.com/results?search_query=dumbbell+floor+press+neutral+grip"},
{b:"B2",n:"Bulgarian Split Squat",s:3,r:"8–10/Seite",l:"5–8 kg",w:"Einbeinige Kraft und Kniesicherheit.",c:"Vorderer Fuß arbeitet, rechts nicht über links hinaus steigern.",v:"https://www.youtube.com/results?search_query=bulgarian+split+squat+technique"},
{b:"C1",n:"Trap-3 Raise",s:3,r:"10–12",l:"leicht",w:"Unterer Trapez und Schulterblattkontrolle.",c:"Sehr leicht starten, Schulter weg vom Ohr.",v:"https://www.youtube.com/results?search_query=trap+3+raise+exercise"},
{b:"C2",n:"Pallof Press",s:3,r:"10/Seite",l:"grün/rot",w:"Anti-Rotation und Core-Stabilität.",c:"Rippen unten, Becken ruhig.",v:"https://www.youtube.com/results?search_query=pallof+press+technique"},
{b:"Finisher",n:"Suitcase Carry",s:3,r:"30–40 s/Seite",l:"14 kg",w:"Seitliche Rumpfstabilität.",c:"Nur eine Hantel, nicht zur Seite kippen.",v:"https://www.youtube.com/results?search_query=suitcase+carry+technique"}],
B:[
{b:"A1",n:"B-Stance RDL",s:3,r:"8–10/Seite",l:"14 kg",w:"Hintere Kette mit Seitenfokus.",c:"Hinterer Fuß nur Stütze, Nacken neutral.",v:"https://www.youtube.com/results?search_query=b+stance+romanian+deadlift+technique"},
{b:"A2",n:"Band Pulldown",s:3,r:"10–12",l:"schwarz + rot",w:"Lat und Rückenbreite.",c:"Ellbogen Richtung Hosentaschen.",v:"https://www.youtube.com/results?search_query=resistance+band+lat+pulldown+technique"},
{b:"B1",n:"Reverse Split Squat",s:3,r:"8/Seite",l:"8 kg",w:"Kniesichere einbeinige Kraft.",c:"Füße bleiben stehen, kontrolliert senken.",v:"https://www.youtube.com/results?search_query=static+split+squat+technique"},
{b:"B2",n:"Schulterdrücken",s:3,r:"8–10",l:"6 kg",w:"Kontrollierte Schulterkraft.",c:"6 kg, Rippen unten, Nacken lang.",v:"https://www.youtube.com/results?search_query=seated+dumbbell+shoulder+press+technique"},
{b:"C1",n:"Lateral Walks",s:3,r:"12/Seite",l:"blau",w:"Gluteus medius und Beinachse.",c:"Kleine Schritte, Bandspannung halten.",v:"https://www.youtube.com/results?search_query=banded+lateral+walk+technique"},
{b:"C2",n:"Reverse Crunch",s:3,r:"10–12",l:"Körpergewicht",w:"Unterer Bauch und Beckenkontrolle.",c:"Becken einrollen, kein Schwung.",v:"https://www.youtube.com/results?search_query=reverse+crunch+proper+form"},
{b:"Finisher",n:"Marching Carry",s:3,r:"30–40 s",l:"14–15 kg",w:"Core, Griffkraft und Kondition.",c:"Langsam marschieren, Schultern tief.",v:"https://www.youtube.com/results?search_query=marching+farmer+carry+technique"}]};
const R=[["Cat Cow","8 Wiederholungen"],["Wall Slides","10 Wiederholungen"],["Band Pull Aparts","15 Wiederholungen"],["Bird Dog","8 pro Seite"],["Dead Bug","8 pro Seite"],["Farmer Hold","2 × 30 Sekunden"]];
let S={p:null,i:0,d:null,t:60,h:null};const $=x=>document.getElementById(x),D=()=>JSON.parse(localStorage.getItem("PS")||'{"sessions":[]}'),save=x=>{localStorage.setItem("PS",JSON.stringify(x));home()};
function show(x){document.querySelectorAll(".view").forEach(v=>v.classList.remove("active"));$(x).classList.add("active");scrollTo(0,0)}
function home(){let d=D(),a=d.sessions||[],l=a.at(-1);$("count").textContent=a.length;$("hws").textContent=l?l.hws+"/10":"–";$("knee").textContent=l?l.knee+"/10":"–";$("last").textContent=l?`${l.date} · Training ${l.plan} · Energie ${l.energy}/5`:"Noch keine Einheit gespeichert."}
document.querySelectorAll(".start").forEach(b=>b.onclick=()=>{S.p=b.dataset.plan;S.i=0;S.d={plan:S.p,date:new Date().toLocaleDateString("de-AT"),exercises:[]};$("title").textContent="Training "+S.p;render();show("train")});
function prev(n){for(let s of (D().sessions||[]).slice().reverse()){let e=s.exercises?.find(x=>x.name===n);if(e)return e}return null}
function render(){let e=P[S.p][S.i];$("progress").textContent=`Übung ${S.i+1} von ${P[S.p].length}`;$("block").textContent=e.b;$("name").textContent=e.n;$("why").textContent=e.w;$("cue").textContent=e.c;$("video").href=e.v;let p=prev(e.n);$("prev").textContent=p?"Letztes Mal: "+p.sets.map(s=>`${s.kg||"–"} kg × ${s.reps||"–"} · RPE ${s.rpe||"–"}`).join(" | "):"Startwert: "+e.l;let c=S.d.exercises[S.i]||{name:e.n,sets:Array.from({length:e.s},()=>({kg:"",reps:"",rpe:""}))};S.d.exercises[S.i]=c;$("sets").innerHTML="";c.sets.forEach((s,i)=>{let r=document.createElement("div");r.className="set";r.innerHTML=`<b>${i+1}</b><label>kg<input inputmode="decimal" value="${s.kg}" data-i="${i}" data-f="kg"></label><label>Wdh.<input inputmode="numeric" value="${s.reps}" data-i="${i}" data-f="reps"></label><label>RPE<input inputmode="numeric" value="${s.rpe}" data-i="${i}" data-f="rpe"></label>`;$("sets").appendChild(r)});$("sets").querySelectorAll("input").forEach(x=>x.oninput=q=>S.d.exercises[S.i].sets[+q.target.dataset.i][q.target.dataset.f]=q.target.value);$("prevBtn").disabled=S.i===0;$("nextBtn").textContent=S.i===P[S.p].length-1?"Abschluss":"Weiter"}
$("nextBtn").onclick=()=>{if(S.i<P[S.p].length-1){S.i++;render()}else show("check")};$("prevBtn").onclick=()=>{if(S.i){S.i--;render()}};$("homeBtn").onclick=()=>show("home");$("backBtn").onclick=()=>show("train");
["hws","knee","energy"].forEach(k=>{$(k+"In").oninput=()=>$(k+"Out").textContent=$(k+"In").value});
$("save").onclick=()=>{S.d.hws=+$("hwsIn").value;S.d.knee=+$("kneeIn").value;S.d.energy=+$("energyIn").value;S.d.note=$("note").value;let d=D();d.sessions.push(S.d);save(d);$("note").value="";show("home")};
function timer(n){S.t=n;$("timer").textContent=`${String(Math.floor(n/60)).padStart(2,"0")}:${String(n%60).padStart(2,"0")}`}document.querySelectorAll(".preset").forEach(b=>b.onclick=()=>timer(+b.dataset.s));$("timerStart").onclick=()=>{clearInterval(S.h);let n=S.t;S.h=setInterval(()=>{timer(--n);if(n<=0){clearInterval(S.h);navigator.vibrate&&navigator.vibrate([200,100,200])}},1000)};
function exp(){let a=document.createElement("a"),b=new Blob([JSON.stringify(D(),null,2)],{type:"application/json"});a.href=URL.createObjectURL(b);a.download=`project-strong-${new Date().toISOString().slice(0,10)}.json`;a.click()}$("export").onclick=exp;$("exportTop").onclick=exp;$("import").onchange=async e=>{try{save(JSON.parse(await e.target.files[0].text()));alert("Backup importiert.")}catch{alert("Datei konnte nicht gelesen werden.")}};
R.forEach(([a,b])=>{let x=document.createElement("div");x.className="resetitem";x.innerHTML=`<b>${a}</b><div>${b}</div>`;$("resetList").appendChild(x)});$("resetStart").onclick=()=>show("reset");$("resetBack").onclick=()=>show("home");if("serviceWorker"in navigator)navigator.serviceWorker.register("sw.js");home();timer(60);